#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ginger
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="G:\\l\\GDB\\CompanyWorkers.mdf")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertAppartments(Appartments instance);
    partial void UpdateAppartments(Appartments instance);
    partial void DeleteAppartments(Appartments instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Ginger.Properties.Settings.Default.G__l_GDB_CompanyWorkers_mdfConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Appartments> Appartments
		{
			get
			{
				return this.GetTable<Appartments>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Appartments")]
	[global::System.Data.Linq.Mapping.InheritanceMappingAttribute(Code="1", Type=typeof(Appartments))]
	[global::System.Data.Linq.Mapping.InheritanceMappingAttribute(Code="2", Type=typeof(chil), IsDefault=true)]
	public partial class Appartments : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DiscKey;
		
		private int _Id;
		
		private string _Rooms;
		
		private string _Street;
		
		private string _NumberAppt;
		
		private string _District;
		
		private System.Nullable<System.DateTime> _DateCall;
		
		private System.Nullable<System.DateTime> _DateFree;
		
		private System.Nullable<bool> _Elite;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDiscKeyChanging(string value);
    partial void OnDiscKeyChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnRoomsChanging(string value);
    partial void OnRoomsChanged();
    partial void OnStreetChanging(string value);
    partial void OnStreetChanged();
    partial void OnNumberApptChanging(string value);
    partial void OnNumberApptChanged();
    partial void OnDistrictChanging(string value);
    partial void OnDistrictChanged();
    partial void OnDateCallChanging(System.Nullable<System.DateTime> value);
    partial void OnDateCallChanged();
    partial void OnDateFreeChanging(System.Nullable<System.DateTime> value);
    partial void OnDateFreeChanged();
    partial void OnEliteChanging(System.Nullable<bool> value);
    partial void OnEliteChanged();
    #endregion
		
		public Appartments()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiscKey", DbType="NVarChar(4000)", IsDiscriminator=true)]
		public string DiscKey
		{
			get
			{
				return this._DiscKey;
			}
			set
			{
				if ((this._DiscKey != value))
				{
					this.OnDiscKeyChanging(value);
					this.SendPropertyChanging();
					this._DiscKey = value;
					this.SendPropertyChanged("DiscKey");
					this.OnDiscKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rooms", DbType="NVarChar(5)")]
		public string Rooms
		{
			get
			{
				return this._Rooms;
			}
			set
			{
				if ((this._Rooms != value))
				{
					this.OnRoomsChanging(value);
					this.SendPropertyChanging();
					this._Rooms = value;
					this.SendPropertyChanged("Rooms");
					this.OnRoomsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Street", DbType="NVarChar(250)")]
		public string Street
		{
			get
			{
				return this._Street;
			}
			set
			{
				if ((this._Street != value))
				{
					this.OnStreetChanging(value);
					this.SendPropertyChanging();
					this._Street = value;
					this.SendPropertyChanged("Street");
					this.OnStreetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NumberAppt", DbType="NVarChar(5)")]
		public string NumberAppt
		{
			get
			{
				return this._NumberAppt;
			}
			set
			{
				if ((this._NumberAppt != value))
				{
					this.OnNumberApptChanging(value);
					this.SendPropertyChanging();
					this._NumberAppt = value;
					this.SendPropertyChanged("NumberAppt");
					this.OnNumberApptChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_District", DbType="NVarChar(150)")]
		public string District
		{
			get
			{
				return this._District;
			}
			set
			{
				if ((this._District != value))
				{
					this.OnDistrictChanging(value);
					this.SendPropertyChanging();
					this._District = value;
					this.SendPropertyChanged("District");
					this.OnDistrictChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateCall", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateCall
		{
			get
			{
				return this._DateCall;
			}
			set
			{
				if ((this._DateCall != value))
				{
					this.OnDateCallChanging(value);
					this.SendPropertyChanging();
					this._DateCall = value;
					this.SendPropertyChanged("DateCall");
					this.OnDateCallChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DateFree", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateFree
		{
			get
			{
				return this._DateFree;
			}
			set
			{
				if ((this._DateFree != value))
				{
					this.OnDateFreeChanging(value);
					this.SendPropertyChanging();
					this._DateFree = value;
					this.SendPropertyChanged("DateFree");
					this.OnDateFreeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Elite", DbType="Bit")]
		public System.Nullable<bool> Elite
		{
			get
			{
				return this._Elite;
			}
			set
			{
				if ((this._Elite != value))
				{
					this.OnEliteChanging(value);
					this.SendPropertyChanging();
					this._Elite = value;
					this.SendPropertyChanged("Elite");
					this.OnEliteChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class chil : Appartments
	{
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    #endregion
		
		public chil()
		{
			OnCreated();
		}
	}
}
#pragma warning restore 1591
